baseURL = 'https://netnate.com'
languageCode = 'en-us'
title = 'netnate'
theme = 'netnate_theme'

[[menus.main]]
name = 'about'
pageRef = '/about'
weight = 10

[[menus.main]]
name = 'posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'tags'
pageRef = '/tags'
weight = 30

[markup]
    [markup.tableOfContents]
        endLevel = 2
    [markup.highlight]
        style = 'catppuccin-mocha'
    [markup.goldmark]
        [markup.goldmark.extensions]
            [markup.goldmark.extensions.passthrough]
                enable = true
                [markup.goldmark.extensions.passthrough.delimiters]
                    block = [['$$', '$$']]
                    inline = [['$', '$']]

[params]
    math = false
    toc = true

[module]
    [module.hugoVersion]
        min = '0.136.5'
